### ISSUE TITLE
The PDF file name used by the Download button is hardcoded

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-documentation-ui#33]
Currently, the Download button at the top of the site is hardcoded to point to `jakarta-ee-tutorial.pdf`, but it should point to the PDF for the current component instead. 

For example, when we integrate the Cargo Tracker Docs (https://github.com/jakartaee/jakartaee-documentation/pull/24), even though the file `cargo-tracker.pdf` is generated, the Download button still points to `jakart-aee-tutorial.pdf`. The file with the hardcoded value is `header-content.hbs`.  It should use the `pdf-name` attribute instead, like so:

This line:

```html
            <a class="button is-primary" href="{{siteRootPath}}/{{page.component.name}}/{{page.componentVersion.displayVersion}}/{{page.attributes.pdf-name}}</a>
```
This would use the attribute defined in `anotral.yml` in the component repo:

```
name: cargotracker-documentation
title: Cargo Tracker Docs
version: 3.0
asciidoc:
  attributes:
    pdf-name: cargo-tracker
    source-language: asciidoc@
    table-caption: false
    xrefstyle: full
nav:
  - modules/ROOT/nav.adoc

```
